--SELECT DISTINCT TAB_NM FROM TDACM00080 WHERE UPPER(JDBC_NM) = 'EOS_DEV'
SELECT DISTINCT COL_NM,COL_HNM FROM TDACM00080 WHERE JDBC_NM = 'EOS_DEV' AND COL_NM LIKE 'LEGEND%'

UPDATE TDACM00080 SET COL_HNM = '섹터순서' WHERE JDBC_NM = 'EOS_DEV' AND COL_NM = 'SECTOR_ORD' AND LENGTH(COL_HNM) < 2

	
